version: '3'
services:
    node:
        build:
            dockerfile: ./node.Dockerfile
            context: .
        image: rmsp/node
        container_name: node-container
        ports:
            - "5000"
        networks: 
            default:
                ipv4_address: "192.168.10.2"

    react:
        build:
            dockerfile: ./react.Dockerfile
            context: .
        image: rmsp/react
        container_name: react-container
        ports:
            - "3000"
        networks: 
            default: 
                ipv4_address: "192.168.10.3"

networks: 
    default:
        driver: bridge
        ipam:
            config:
              - subnet: 192.168.10.0/24
                